"""Add books table

Revision ID: 7b49481bf438
Revises: f879d5d41f91
Create Date: 2019-10-10 07:41:34.796572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b49481bf438'
down_revision = 'f879d5d41f91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
