"""Adding books to Book table

Revision ID: c7a2d0f9b089
Revises: b78cdaa6e6ec
Create Date: 2019-10-11 07:32:10.453708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7a2d0f9b089'
down_revision = 'b78cdaa6e6ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
